name: "training_dbt"
version: "1.0.0"

profile: "training_dbt"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  training_dbt:
    +materialized: table
    staging:
      +schema: staging
      +docs:
        node_color: green

    intermediate:
      +schema: intermediate
      +docs:
        node_color: "red"
    mart:
      +schema: mart
      +docs:
        node_color: "AE2012"

seeds:
  +schema: seeds
  +docs:
    node_color: "blue"

sources:
  +materialized: table
  +schema: seeds
  +docs:
    node_color: "cyan"
