[project]
name = "ifco-digital-training-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "databricks>=0.2",
    "dbt-core>=1.9.2",
    "dbt-databricks>=1.9.5",
]
