name: Deployment on a merge

on:
  push:
    branches: # Which branches will deploy?
    - 'main'
  workflow_dispatch:



jobs:
  test:
    name: "DBT Tests"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Install DBT Dependencies"
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt test --select 'test_type:unit'"
          dbt_project_folder: "."

      - name: "Execute DBT Tests"
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt test --select 'test_type:unit'"
          dbt_project_folder: "."

  deploy:
    needs: test
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Install Databricks CLI"
        uses: databricks/setup-cli@main

      - name: "Install DBT Dependencies"
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt deps"
          dbt_project_folder: "."

      - name: "Download Databricks Code Into Runner"
        run: |
          databricks workspace export-dir --overwrite '/Shared/Digital/.bundle/asset_accelerator/files/target' target_prod
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_BUNDLE_ENV: replace_me # Add bundle

      - name: "DBT Run On Modified Models"
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt build --select 'state:modified+1' --defer --state ./target_prod"
          dbt_project_folder: "."

      - name: "Deploy Bundle To Databricks"
        run: databricks bundle deploy
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_BUNDLE_ENV: replace_me # Add bundle

      - name: "Deploy Profiles.yml"
        run: |
          databricks workspace import --overwrite --format AUTO --file profiles.yml '/Shared/Digital/.bundle/asset_accelerator/files/profiles.yml'
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_BUNDLE_ENV: replace_me # Add bundle

      - name: Deploy DBT target folder
        run: |
          databricks workspace import-dir --overwrite target '/Shared/Digital/.bundle/asset_accelerator/files/target'
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_BUNDLE_ENV: replace_me # Add bundle

