name: Pull Request Linting

on:
  pull_request:
    types: [opened, edited]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check branch name
        run: |
          BRANCH_NAME=${{ github.head_ref }}
          if [[ ! "$BRANCH_NAME" =~ ^s[0-9]+_core/ ]]; then
          echo "Branch name must start with the following format 's[number_of_the_training_session]_core/[name_of_the_session]'"
          exit 1
          fi
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Run yamllint
        run: |
          echo "Running yamllint..."
          yamllint .

  test:
    name: "dbt unit test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate profile to serverless sql warehouse
        run: |
          sed -e 's|ENVIRONMENT|asset_accelerator|' \
              -e 's|PUT YOUR HOST|${{ secrets.DATABRICKS_HOST }}|' \
              -e 's|PUT YOUR PATH|${{ secrets.DATABRICKS_SERVERLESS_HTTP_PATH }}|' \
              -e 's|PUT YOUR TOKEN|${{ secrets.DATABRICKS_TOKEN }}|' \
              -e 's|PUT YOUR THREADS|8|' \
              ./profiles.yml.dist > ./profiles.yml \
              && echo -e "\n      database: nam" >>  ./profiles.yml

      - name: dbt-deps
        uses: bzillins/dbt-action@master
        with:
          dbt_command: "dbt deps"
          dbt_project_folder: "."

      - name: dbt-test
        uses: bzillins/dbt-action@master
        with:
          dbt_command: "dbt test --select 'test_type:unit'"
          dbt_project_folder: "."
