version: 2

models:
  - name: orders_raw
    description: "Raw ingested orders"
    columns:
      - name: customer_name
        description: "The name of a customer"
        data_tests:
          - not_null

  - name: orders_daily
    description: "Number of orders by day"
    columns:
      - name: order_date
        description: "The date on which orders took place"
        data_tests:
          - unique
          - not_null
    tests:
      - unit_test_example_orders_daily:
          inputs:
            - name: orders_raw
              data:
                - customer_name: "John Doe"
                  order_datetime: "1609459200"  # Example UNIX timestamp
                  order_number: "12345"
                - customer_name: "Jane Smith"
                  order_datetime: "1609545600"
                  order_number: "67890"
                - customer_name: "Alice Johnson"
                  order_datetime: "1609459200"
                  order_number: "54321"
          expected_output:
            - name: expected_output_table
              data:
                - order_date: "2021-01-01"
                  number_of_orders: 2
                - order_date: "2021-01-02"
                  number_of_orders: 1